"""Posts structured review comments back to a GitHub PR."""
from __future__ import annotations

import logging

from github import Github, GithubException
from github.PullRequest import PullRequest

from config import settings
from models.review import ExtractedQuery, Issue, ReviewResult

logger = logging.getLogger(__name__)

_SEVERITY_EMOJI = {"low": "🟡", "medium": "🟠", "high": "🔴"}
_CONFIDENCE_LABEL = {"low": "low confidence", "medium": "medium confidence", "high": "high confidence"}


class PRCommenter:
    """Posts inline and summary review comments to a GitHub pull request."""

    def __init__(self) -> None:
        self._gh = Github(settings.github_token)

    def post_review(
        self,
        owner: str,
        repo_name: str,
        pr_number: int,
        results: list[tuple[ExtractedQuery, ReviewResult]],
        commit_sha: str,
    ) -> None:
        """
        Post inline comments per issue and a summary comment on the PR.

        Args:
            owner: Repository owner (user or org).
            repo_name: Repository name.
            pr_number: Pull request number.
            results: List of (query, result) pairs from the analyser.
            commit_sha: The HEAD commit SHA of the PR (required for inline comments).
        """
        repo = self._gh.get_repo(f"{owner}/{repo_name}")
        pr: PullRequest = repo.get_pull(pr_number)
        commit = repo.get_commit(commit_sha)

        total_issues = sum(len(r.issues) for _, r in results)
        if total_issues == 0:
            logger.info("No issues found — posting clean bill of health.")
            pr.create_issue_comment(_clean_comment())
            return

        # Post each issue as an individual inline comment.
        # Posting individually means one bad line number won't block all others.
        inline_count = 0
        for query, result in results:
            if not result.issues or query.line <= 0:
                continue
            for issue in result.issues:
                body = _format_inline_issue(issue, result)
                try:
                    pr.create_review_comment(
                        body=body,
                        commit=commit,
                        path=query.file,
                        line=query.line,
                        side="RIGHT",
                    )
                    inline_count += 1
                    logger.info(
                        "Inline comment posted: %s:%d [%s]",
                        query.file, query.line, issue.type,
                    )
                except GithubException as exc:
                    logger.warning(
                        "Inline comment failed for %s:%d [%s] (status=%s): %s",
                        query.file, query.line, issue.type, exc.status, exc.data,
                    )

        logger.info("Posted %d inline comment(s).", inline_count)


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------


def _format_inline_issue(issue: Issue, result: ReviewResult) -> str:
    emoji = _SEVERITY_EMOJI.get(issue.severity, "⚪")
    confidence = _CONFIDENCE_LABEL.get(issue.confidence, issue.confidence)
    lines = [
        f"{emoji} **[{issue.type}]** _{confidence}_",
        "",
        issue.description,
        "",
        f"**Suggestion:** {issue.suggestion}",
    ]
    if result.optimized_query:
        lines += [
            "",
            "**Optimized query:**",
            f"```sql\n{result.optimized_query}\n```",
        ]
    return "\n".join(lines)



def _clean_comment() -> str:
    return (
        "## 🔍 Prism Code Review\n\n"
        "✅ No issues detected in this PR.\n\n"
        "---\n"
        "_Review generated by [Prism](https://github.com/ssaini24/prism). Suppress a block with `-- prism: ignore`._"
    )
